export const EXR_MAGIC = 20000630; // 0x762f3101

export const COMPRESSION_NAMES: Record<number, string> = {
  0: 'NO_COMPRESSION',
  1: 'RLE_COMPRESSION',
  2: 'ZIPS_COMPRESSION',
  3: 'ZIP_COMPRESSION',
  4: 'PIZ_COMPRESSION',
  5: 'PXR24_COMPRESSION',
  6: 'B44_COMPRESSION',
  7: 'B44A_COMPRESSION',
  8: 'DWAA_COMPRESSION',
  9: 'DWAB_COMPRESSION',
};
